### ISSUE TITLE
README has wrong attribute names for some Team attributes

### ISSUE THREAD

**Issue by rsmith54** [rbarton65/espnff#7]
I was just playing around with this (very cool!), and it seems like some of the ```Team``` attribute names are wrong in the README.  For example, ```points_for``` should be ```pointsFor``` (similarly for a few of the others).

I'm not sure which way you want (```points_for``` is probably more pythonic), so probably it's best to follow the README and switch the attributes.  If you are interested in help on this project I could submit a PR.

**Comment by rbarton65** [comment]
Hi! When I initially created this package I was using `pointsFor` instead of `points_for`, and like you said, I wanted to be more pythonic. In `v1.1.0` I gave a deprecation warning that I would be switching to `points_for` (again, similarly for a few others), and in `v1.2.0` I removed attributes with that syntax. You can read the changelog [here](https://github.com/rbarton65/espnff/blob/master/CHANGELOG.md).

If you're on any version earlier than `1.2.0` I suggest updating the package to the current version! Let me know if that helps.

**Comment by rsmith54** [comment]
Ah okay! I quickly checked the changelog but obviously not close enough :) thanks for your quick response.
